# https://docs.dapr.io/reference/components-reference/supported-bindings/rabbitmq/
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding-rabbitmq
  namespace: default
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
  - name: queueName
    value: queue-test
  - name: host
    value: amqp://test-user:test-password@localhost:5672
  - name: durable
    value: true
  - name: deleteWhenUnused
    value: false
  - name: ttlInSeconds
    value: 60
  - name: prefetchCount
    value: 1
  - name: exclusive
    value: false
  - name: maxPriority
    value: 5