apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding-redis
  namespace: default
spec:
  type: bindings.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: 
  - name: enableTLS
    value: false